### ISSUE TITLE
Wrong data in help

### ISSUE THREAD

**Issue by Ku6ep** [testappio/cli#2]
On embedded help `ta-cli -h` show this sample config: 
`config.json
 {
	"api_token": "Your API Token",
	"appID": "Your App ID",
	"release": "both",
	"apk": "/path/to/app.apk",
	"ipa": "/path/to/app.ipa",
	"notify": "yes"
  }
`
but first row must be `"apiToken":"Your API Token"`

**Comment by Massad** [comment]
@Ku6ep thank you for reporting. It fixed and you can update it from this:

`curl -Ls https://raw.githubusercontent.com/testappio/cli/main/macos/install.sh | sh`
