### ISSUE TITLE
Error when trying to do a release from a container

### ISSUE THREAD

**Issue by joaozanutto** [testappio/cli#4]
Hello! I'm trying to run the 1.0.1 binary release of the `ta-cli`  from inside a container but I keep getting the error message below

```
root@0aa8f31dd1a2:/ta-cli_linux# ./ta-cli publish --apk=$(pwd)/demo.apk --api_token=<MY_API_TOKEN> --app_id=<MY_APP_ID>
Using config file: /root/.ta-cli.json 


-------------- Releasing for Android only --------------
======> Preparing the release....
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x848ba3]

goroutine 1 [running]:
ta-cli/cmd.preRelease(0x7ffc9b7fe941, 0x24, 0x7ffc9b7fe96f, 0xa, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/ta-cli/cmd/publish.go:222 +0x103
ta-cli/cmd.doAndroid(0x7ffc9b7fe941, 0x24, 0x7ffc9b7fe96f, 0xa, 0x7ffc9b7fe91e, 0x16, 0x1, 0x0, 0x7986b3)
	/go/src/ta-cli/cmd/publish.go:560 +0xf4
ta-cli/cmd.doPublish(0x0, 0x7)
	/go/src/ta-cli/cmd/publish.go:509 +0x7bb
ta-cli/cmd.glob..func3(0xc3dde0, 0xc000095c20, 0x0, 0x3, 0x0, 0x0)
	/go/src/ta-cli/cmd/publish.go:71 +0x45
github.com/spf13/cobra.(*Command).execute(0xc3dde0, 0xc000095bc0, 0x3, 0x3, 0xc3dde0, 0xc000095bc0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc3e060, 0x0, 0xffffffff, 0xc000082058)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
ta-cli/cmd.Execute(...)
	/go/src/ta-cli/cmd/root.go:61
main.main()
	/go/src/ta-cli/main.go:6 +0x2e
```

The Dockerfile for this container is:

```
FROM ubuntu

COPY . /root

RUN apt update && apt install bash curl unzip -y \
    && curl -Ls https://github.com/testappio/cli/releases/download/v1.0.1/ta-cli_linux.zip -o ta-cli.zip \
    && unzip ta-cli.zip

WORKDIR /ta-cli_linux

RUN curl -L https://www.apkmirror.com/apk/sample-developer/test-dpc/test-dpc-8-0-1-release/ -o demo.apk \
    && ./ta-cli publish --apk=$(pwd)/demo.apk --api_token=<API_TOKEN> --app_id=<APP_ID>
```

and here's the content for the .ta-cli.json:

```
{
    "api_token": "<api_token>",
    "app_id": "<app_id>",
    "release": "android",
    "apk": "/",
    "ipa": "",
    "notify": "yes"
  }
```

**Comment by Massad** [comment]
@joaozanutto did you try to upload the same APK in [portal](https://portal.testapp.io)?

**Comment by joaozanutto** [comment]
@Massad yes, in fact I did upload it using the `ta-cli` in my host machine and it did work perfectly, the issue is happening when I try to run it on the docker container, and we are looking forward to have this container running so we can integrate this to our CI in GitLab

**Comment by Massad** [comment]
From the output above it appears that there's an issue in extracting the info from the APK.

I will try to replicate the same environment and let you know.

But can't promise any time soon because we are currently releasing our new features (feedback, install page,...)

Sorry for the inconvenience!

**Comment by joaozanutto** [comment]
@Massad To update you on this issue, I tested setting the values for the `apk`, `api_key` and `app_id` directly in the `.ta-cli.json` file instead of overriding their values within the run command (using flags, like `--apk`) and it **worked**.

So I guess something might have gone wrong when trying to override the values, which is something that we want to do since it will make the CI integration much easier.

**Comment by Massad** [comment]
> --apk=$(pwd)/demo.apk

@joaozanutto I believe the issue is with line because it will not execute `$(pwd)`

I will try to find a better option, possibly just `--apk=demo.apk` and the CLI will pick the full path of it - I will keep you updated.

I am currently working on Github Action and maybe you could use it if you are using actions to build your app.

**Comment by Massad** [comment]
@joaozanutto I've released a new version for the CLI (It will not solve your issue because of `$(pwd)` but it will detect the exact issue)

And Github Action: https://github.com/testappio/github-action

Let me know if that worked for you or not and message us in the chat so I can know your team and help you out more :)
